repos:
-   repo: local
    hooks:
    -   id: do-nothing
        name: "Hook que no hace nada"
        entry: echo "Este hook no valida nada"
        language: system
        always_run: true
        pass_filenames: false
        verbose: true