services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # consola web
    volumes:
      - ./data:/data        # almacenamiento persistente
      - ./config:/root/.minio # configuración persistente
    environment:
      MINIO_ROOT_USER: admin       # usuario de acceso
      MINIO_ROOT_PASSWORD: admin123 # contraseña de acceso
    command: server /data --console-address ":9001"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__API_KEY: "super_secret_api_key"
    volumes:
      - ./qdrant_storage:/qdrant/storage